version: 2
jobs:
   test:
     docker:
       - image: circleci/node:8.9.3
     steps:
       - checkout
       - run:
          name: Install npm
          command: npm install
       - run:
          name: Run Test (testlint)
          command: npm run test
   build:
     docker:
       - image: circleci/python:3.6.1
     working_directory: ~/repo
     steps:
       - checkout
       - add_ssh_keys:
           fingerprints:
            - "0c:05:da:44:fd:23:6e:85:c4:f4:4a:d1:ee:68:35:03"
       - run:
          name: Meet the requirements
          command: |
            sudo pip install pipenv
            pipenv install
       - run:
          name: Deploy to gh-pages
          command: |
            pipenv run python -m mkdocs gh-deploy
workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
